[project]
name = "hntags-com"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "firebase>=4.0.1",
    "jinja2>=3.1.6",
    "ollama>=0.5.1",
]
