name: Push to Main
on:
  push:
    branches:
      - main

jobs:
  login-and-publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build image
        run: docker build -t hntags:latest .